import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import Header from '@/widgets/Header/Header';
import Footer from '@/widgets/Footer/Footer';
import { getSocials } from '@/api/getSocials';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const socials = await getSocials();

  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer socials={socials} />
      </body>
    </html>
  );
}
