import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import Header from '@/widgets/Header/Header';
import Footer from '@/widgets/Footer/Footer';
import { getSocials } from '@/api/getSocials';
import { getStrapiMedia } from '@/utils/strapiMedia';
import { SocialsAPIResponse } from '@/widgets/Socials/Socials.d';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const { data } = await getSocials() as unknown as SocialsAPIResponse;
  const socialData = data.attributes.Socials;

  const formatedSocials = socialData.map(item => ({
    icon: getStrapiMedia(item.icon.data.attributes.url) as string,
    name: item.name as string,
    url: item.url as string,
  }));

  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer socials={formatedSocials} />
      </body>
    </html>
  );
}
